// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'app/database/entities/audio_entity.dart';
import 'app/database/entities/video_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 598335344674949174),
      name: 'AudioEntity',
      lastPropertyId: const IdUid(4, 3753845151845557475),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2764103454951905419),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7288004451345443356),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4423364527349032848),
            name: 'autor',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3753845151845557475),
            name: 'favorite',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 7824376707995856932),
      name: 'VideoEntity',
      lastPropertyId: const IdUid(4, 3798569305028061224),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 619109641363573441),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3210483710514237799),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7342887556046093820),
            name: 'autor',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 3798569305028061224),
            name: 'favorite',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 7824376707995856932),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    AudioEntity: EntityDefinition<AudioEntity>(
        model: _entities[0],
        toOneRelations: (AudioEntity object) => [],
        toManyRelations: (AudioEntity object) => {},
        getId: (AudioEntity object) => object.id,
        setId: (AudioEntity object, int id) {
          object.id = id;
        },
        objectToFB: (AudioEntity object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final autorOffset = fbb.writeString(object.autor);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, autorOffset);
          fbb.addBool(3, object.favorite);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = AudioEntity()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..autor = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..favorite =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);

          return object;
        }),
    VideoEntity: EntityDefinition<VideoEntity>(
        model: _entities[1],
        toOneRelations: (VideoEntity object) => [],
        toManyRelations: (VideoEntity object) => {},
        getId: (VideoEntity object) => object.id,
        setId: (VideoEntity object, int id) {
          object.id = id;
        },
        objectToFB: (VideoEntity object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final autorOffset = fbb.writeString(object.autor);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, autorOffset);
          fbb.addBool(3, object.favorite);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = VideoEntity()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..autor = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..favorite =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [AudioEntity] entity fields to define ObjectBox queries.
class AudioEntity_ {
  /// see [AudioEntity.id]
  static final id =
      QueryIntegerProperty<AudioEntity>(_entities[0].properties[0]);

  /// see [AudioEntity.name]
  static final name =
      QueryStringProperty<AudioEntity>(_entities[0].properties[1]);

  /// see [AudioEntity.autor]
  static final autor =
      QueryStringProperty<AudioEntity>(_entities[0].properties[2]);

  /// see [AudioEntity.favorite]
  static final favorite =
      QueryBooleanProperty<AudioEntity>(_entities[0].properties[3]);
}

/// [VideoEntity] entity fields to define ObjectBox queries.
class VideoEntity_ {
  /// see [VideoEntity.id]
  static final id =
      QueryIntegerProperty<VideoEntity>(_entities[1].properties[0]);

  /// see [VideoEntity.name]
  static final name =
      QueryStringProperty<VideoEntity>(_entities[1].properties[1]);

  /// see [VideoEntity.autor]
  static final autor =
      QueryStringProperty<VideoEntity>(_entities[1].properties[2]);

  /// see [VideoEntity.favorite]
  static final favorite =
      QueryBooleanProperty<VideoEntity>(_entities[1].properties[3]);
}
